In [3]:
help(np.ndarray)

NameError: name 'np' is not defined

In [5]:
pip install numpy

     ---------------------------------------- 0.0/59.7 kB ? eta -:--:--
     ---------------------------------- ----- 51.2/59.7 kB 1.3 MB/s eta 0:00:01
     ---------------------------------------- 59.7/59.7 kB 1.1 MB/s eta 0:00:00
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 10.5 MB/s eta 0:00:02
   ---- ----------------------------------- 1.4/12.6 MB 17.6 MB/s eta 0:00:01
   ----------- ---------------------------- 3.5/12.6 MB 28.0 MB/s eta 0:00:01
   ---------------------- ----------------- 7.0/12.6 MB 40.5 MB/s eta 0:00:01
   ----------------------------- ---------- 9.1/12.6 MB 41.7 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.6 MB 72.6 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 65.5 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import numpy as np

a= np.ndarray((2,3))
a

array([[ 4.64583300e-308,  4.66664552e-308, -2.57703408e+010],
       [-4.70231646e-064,  2.26262303e-319,  7.56571287e-307]])

In [18]:
import numpy as np

a=np.ndarray((3,2), dtpye=int)
a

TypeError: 'dtpye' is an invalid keyword argument for ndarray()

In [9]:
np.ndarray?

Init signature: np.ndarray(self, /, *args, **kwargs)
Docstring:     
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object that can be interpreted as a numpy data type.
buffer : object exposing buffer int

In [10]:
import numpy as np

a=np.ndarray(shape=(2,2), dtype=int)
a

array([[25895968444448860, 23925768161198147],
       [32370111954616435, 16044279834148956]])

In [11]:
print(a.shape)
print(a.ndim)
print(a.size)
print(a.itemsize)
print(a.dtype)
print(a.nbytes)

(2, 2)
2
4
8
int64
32


In [12]:
a.data

In [13]:
help(np.dtype)

Help on class dtype in module numpy:

class dtype(builtins.object)
 |  dtype(dtype, align=False, copy=False, [metadata])
 |
 |  Create a data type object.
 |
 |  A numpy array is homogeneous, and contains elements described by a
 |  dtype object. A dtype object can be constructed from different
 |  combinations of fundamental numeric types.
 |
 |  Parameters
 |  ----------
 |  dtype
 |      Object to be converted to a data type object.
 |  align : bool, optional
 |      Add padding to the fields to match what a C compiler would output
 |      for a similar C-struct. Can be ``True`` only if `obj` is a dictionary
 |      or a comma-separated string. If a struct dtype is being created,
 |      this also sets a sticky alignment flag ``isalignedstruct``.
 |  copy : bool, optional
 |      Make a new copy of the data-type object. If ``False``, the result
 |      may just be a reference to a built-in data-type object.
 |  metadata : dict, optional
 |      An optional dictionary with dtype meta

In [14]:
import numpy as np

a=np.array([1,2,3], dtype=int)
a

array([1, 2, 3])

In [15]:
type(a)

numpy.ndarray

In [16]:
print(a.shape)
print(a.ndim)
print(a.dtype)

(3,)
1
int64


In [17]:
print(a.size)
print(a.itemsize)
print(a.nbytes)

3
8
24


In [19]:
a.data

In [20]:
np.array(1,2,3) #오류

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [21]:
np.array([1,'py',3.14])

array(['1', 'py', '3.14'], dtype='<U32')

In [22]:
import numpy as np

unicode_arrary = np.array(['가나다','라마바','사아자'],dtype='<U32')
unicode_arrary

array(['가나다', '라마바', '사아자'], dtype='<U32')

In [24]:
unicode_arrary = np.array(['가나다라마'*7,'라마바','사아자'],dtype='<U64')
unicode_arrary

array(['가나다라마가나다라마가나다라마가나다라마가나다라마가나다라마가나다라마', '라마바', '사아자'], dtype='<U64')

In [25]:
lang = np.array(['파이썬','자바','씨'])
lang

array(['파이썬', '자바', '씨'], dtype='<U3')

In [26]:
a = np.array([1,2,3],dtype=float)
a

array([1., 2., 3.])

In [27]:
b =np.array([1,2.5,3])
b

array([1. , 2.5, 3. ])

In [28]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

    Return evenly spaced values within a given interval.

    ``arange`` can be called with a varying number of positional arguments:

    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.

    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.

    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.

    See the Warn

In [29]:
import numpy as np

print(np.arange(3)) # >>(0,3,1)
print(np.arange(3,7)) # >> (3,7,1)
print(np.arange(3,7,2)) 

[0 1 2]
[3 4 5 6]
[3 5]


In [30]:
import numpy as np

print(np.arange(2.0))  # (0.0,2.0,1.0)
print(np.arange(2.0,6.5)) # (2.0,6.5,1.0)
print(np.arange(2.0,6.5,0.8))

[0. 1.]
[2. 3. 4. 5. 6.]
[2.  2.8 3.6 4.4 5.2 6. ]


In [31]:
np.arange(0,5,0.5,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [33]:
np.arange(-3,3,0.5,dtype=int)

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [34]:
import numpy as np
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
np.reshape(a,(2,6))
#a.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [37]:
np.reshape(2,6)

ValueError: cannot reshape array of size 1 into shape (6,)

In [38]:
b= np.array([1,2,3,4,5,6]).reshape(3,2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
np.reshape(b,(2,-1)) # np.reshape(b, (2,3))

np.reshape(b, (5,-1))  #ERROR

np.reshape(b,(6,-1)) # np.reshape(b, (6,-1))

ValueError: cannot reshape array of size 6 into shape (5,newaxis)

In [40]:
np.linspace(2.0, 3.0) #(2.0, 3.0, 50)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [42]:
np.linspace(2.0, 3.0, retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 np.float64(0.02040816326530612))

In [43]:
print( (3-2) / (50-1))

0.02040816326530612


In [44]:
np.linspace(2.0, 3.0, endpoint=False,retstep=True)

(array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
        2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
        2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
        2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
        2.88, 2.9 , 2.92, 2.94, 2.96, 2.98]),
 np.float64(0.02))

In [45]:
print( (3-2)/ 50)

0.02


In [46]:
np.linspace(2.0,3.0,num=5,retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), np.float64(0.25))

In [47]:
np.linspace(2.0,3.0,num=5,endpoint=False,retstep=True)

(array([2. , 2.2, 2.4, 2.6, 2.8]), np.float64(0.2))

In [48]:
# 0.4가 나오지 않아야 하나 부동소수의 문제로
np.arange(0.1,0.4,0.1)

array([0.1, 0.2, 0.3, 0.4])

In [49]:
np.arange(1,4,1)/10.0

array([0.1, 0.2, 0.3])

In [50]:
np.linspace(0.1, 0.4, 3, endpoint=False)

array([0.1, 0.2, 0.3])

In [51]:
np.linspace(0.1, 0.4, 4)

array([0.1, 0.2, 0.3, 0.4])

In [52]:
import numpy as np

a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [53]:
a.dtype

dtype('float64')

In [ ]:
np.zeros?

In [55]:
np.zeros((5), dtype=int)

array([0, 0, 0, 0, 0])

In [56]:
np.zeros((2,1))

array([[0.],
       [0.]])

In [58]:
b.shape

(3, 2)

In [59]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [60]:
np.ones((2,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [61]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
np.eye(2,dtype=int)

array([[1, 0],
       [0, 1]])

In [63]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [67]:
a=np.eye(3,4,1)
a


array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [68]:
b=np.eye(3,4,-1)
b

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [66]:
np.eye(3,4,-2)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.]])

In [69]:
np.full((2,3),100)

array([[100, 100, 100],
       [100, 100, 100]])

In [70]:
np.full((2,3),(1,2,3))

array([[1, 2, 3],
       [1, 2, 3]])

In [71]:
np.full((2,3),(1,2))

ValueError: could not broadcast input array from shape (2,) into shape (2,3)

In [73]:
np.full((3,4),range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [79]:
np.full([4,3,], fill_value=np.arange(4).reshape(4,1)) #[0]
                                                      #[1]
                                                      #[2]
                                                      #[3]

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [80]:
np.empty(3)

array([4.9e-324, 9.9e-324, 1.5e-323])

In [81]:
np.empty([2,2])

array([[0.0e+000, 4.9e-324],
       [9.9e-324, 1.5e-323]])

In [82]:
np.empty([2,3], dtype=int)

array([[25895968444448860, 23925768161198147, 32370111954616435],
       [16044279834148956, 18296268626395181, 27303364806049904]])

In [83]:
np.empty((3,2,3), int)

array([[[            0, 1673663034368,             0],
        [            0,             0,             0]],

       [[            0, 1673648816800, 1673648815616],
        [1673648815936, 1673661488912,             0]],

       [[            0,             0,             0],
        [            0,             0,             0]]])

In [86]:
import numpy as np

a = np.arange(8).reshape(2,4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [87]:
np.zeros_like(a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [88]:
np.ones_like(a)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [89]:
np.full_like(a,5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [90]:
np.full_like(a,range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

In [91]:
import numpy as np

a =np.arange(3)
a


array([0, 1, 2])

In [92]:
print(a+2)
print(a-2)
print(a*2)
print(a/2)


[2 3 4]
[-2 -1  0]
[0 2 4]
[0.  0.5 1. ]


In [94]:
a =np.arange(1,7).reshape(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [100]:
b=np.full_like(a,[1,2])
b

array([[1, 2],
       [1, 2],
       [1, 2]])

In [98]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)


[[2 4]
 [4 6]
 [6 8]]
[[0 0]
 [2 2]
 [4 4]]
[[ 1  4]
 [ 3  8]
 [ 5 12]]
[[1. 1.]
 [3. 2.]
 [5. 3.]]


In [101]:
a =np.arange(4)
a

array([0, 1, 2, 3])

In [102]:
b = np.arange(0.5,4,1)
b

array([0.5, 1.5, 2.5, 3.5])

In [103]:
a += b #a =a + b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [104]:
b +=a
b

array([0.5, 2.5, 4.5, 6.5])

In [106]:
a =np.full((2,3),{1,2,3})
a

array([[{1, 2, 3}, {1, 2, 3}, {1, 2, 3}],
       [{1, 2, 3}, {1, 2, 3}, {1, 2, 3}]], dtype=object)

In [107]:
b=np.full((3,2),[2,1])
b

array([[2, 1],
       [2, 1],
       [2, 1]])

In [ ]:
a @ b

In [ ]:
a.dot(b)

In [ ]:
b.dot(a)

In [113]:
import numpy as np 

print(np.matmul(a,b))
print(np.matmul(b,a))

TypeError: unsupported operand type(s) for *: 'set' and 'int'

In [114]:
a= np.array([[10,20],[5,8],[1,2]])
a

array([[10, 20],
       [ 5,  8],
       [ 1,  2]])

In [115]:
a.sum()

np.int64(46)

In [116]:
a.sum(axis=0)

array([16, 30])

In [117]:
a.sum(axis=1)

array([30, 13,  3])

In [118]:
import numpy as np 

print(np.sum(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

46
[16 30]
[30 13  3]


In [120]:
a = np.array([[3,5,8],[1,2,3]])
a

array([[3, 5, 8],
       [1, 2, 3]])

In [121]:
#일차원으로 펼펴서 계산
a.cumsum()
# [3,5,8,1,2,3]
# >> [3+5, 3+5+8, 3+5+8+1, 3+5+8+1+2, 3+5+8+1+2+3]

array([ 3,  8, 16, 17, 19, 22])

In [122]:
a.cumsum(axis=0) #행을 따라 세로로 합산
# [3,5,8]
# [1,2,3]
# >> [3,5,8]
# >> [3+1,5+2,8+3]

array([[ 3,  5,  8],
       [ 4,  7, 11]])

In [123]:
a.cumsum(axis=1) #열을 따라 가로로 합산
# [3,3+5,3+5+8]
# [1,1+2,1+2+3]

array([[ 3,  8, 16],
       [ 1,  3,  6]])

In [124]:
import numpy as np

a = np.array((1,4,9))
np.sqrt(a)

array([1., 2., 3.])

In [125]:
np.log(a)

array([0.        , 1.38629436, 2.19722458])

In [126]:
import numpy as np

a = np.array([1,4,9])
a

array([1, 4, 9])

In [127]:
b = np.full_like(a,2)
b

array([2, 2, 2])

In [128]:
np.add(a,b)

array([ 3,  6, 11])

In [129]:
np.divide(a,b)

array([0.5, 2. , 4.5])

In [130]:
np.power(a,b)

array([ 1, 16, 81])

In [131]:
import numpy as np

a = np.power(np.arange(10),2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [132]:
print(a[3])
print(a[-2])

9
64


In [133]:
print(a[1:4])
print(a[-5:-1])

[1 4 9]
[25 36 49 64]


In [134]:
print(a[8:2:-1])
print(a[-1:-7:-1])

[64 49 36 25 16  9]
[81 64 49 36 25 16]


In [135]:
a[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0])

In [136]:
a[::-2]

array([81, 49, 25,  9,  1])

In [137]:
a[2:5]=-100  #[-100,-100,-100]
a

array([   0,    1, -100, -100, -100,   25,   36,   49,   64,   81])

In [138]:
a[2:5]= [-5,-5,-15]
a

array([  0,   1,  -5,  -5, -15,  25,  36,  49,  64,  81])

In [141]:
a[2:5]= [-5,-5,]
a

ValueError: could not broadcast input array from shape (2,) into shape (3,)

In [140]:
a[2:6]=[-5,-5]

ValueError: could not broadcast input array from shape (2,) into shape (4,)

In [142]:
a[2:5]=-10
a

array([  0,   1, -10, -10, -10,  25,  36,  49,  64,  81])

In [143]:
b = np.array([5]*10)
b

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [144]:
b[::2]=-10
b

array([-10,   5, -10,   5, -10,   5, -10,   5, -10,   5])

In [145]:
b[::2] = np.arange(5)
b

array([0, 5, 1, 5, 2, 5, 3, 5, 4, 5])

In [146]:
b[::2] = np.arange(7)
b

ValueError: could not broadcast input array from shape (7,) into shape (5,)

In [147]:
a =np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [148]:
a[3] # a[3,:]

array([18, 19, 20, 21, 22, 23])

In [149]:
a[-1]

array([24, 25, 26, 27, 28, 29])

In [153]:
a[-2,:]

array([18, 19, 20, 21, 22, 23])

In [154]:
a[-2, ]

array([18, 19, 20, 21, 22, 23])

In [155]:
a[2:4]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [156]:
a[1:5:2]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [157]:
a[,1]

SyntaxError: invalid syntax (3819423678.py, line 1)

In [158]:
a[:,1]

array([ 1,  7, 13, 19, 25])

In [159]:
a[:,1:6]

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

In [161]:
a[:,::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [162]:
a[2,4]

np.int64(16)

In [163]:
a[::2]

array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17],
       [24, 25, 26, 27, 28, 29]])

In [165]:
a[::]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [166]:
a[2][4]

np.int64(16)

In [167]:
a[1:3,2:5]

array([[ 8,  9, 10],
       [14, 15, 16]])

In [168]:
a[:,:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [169]:
a[:, ]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [170]:
a[:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [171]:
a[::-1,::-1]

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [172]:
# 마지막 행과 열을 제외한 배열 반환
a[:-1,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

In [176]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [177]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [178]:
a[:,1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [179]:
a[:,1,1]

array([ 5, 17])

In [180]:
a[:,:,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [181]:
a[:,:,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [182]:
a[...,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [183]:
a[1,...,1]

array([13, 17, 21])

In [184]:
a[0,...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [185]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [186]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [187]:
a[:,:,2:]

array([[[ 2,  3],
        [ 6,  7],
        [10, 11]],

       [[14, 15],
        [18, 19],
        [22, 23]]])

In [188]:
a[:,:,3:]

array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [23]]])

In [189]:
a = np.arange(12).reshape(2,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [190]:
b =a.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [192]:
b[0]=100
b

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [193]:
a

array([[[100,   1],
        [  2,   3],
        [  4,   5]],

       [[  6,   7],
        [  8,   9],
        [ 10,  11]]])

In [194]:
a =np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [195]:
np.transpose(a)


array([[1, 4],
       [2, 5],
       [3, 6]])

In [196]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [197]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [198]:
np.transpose(a,(0,1))

array([[1, 2, 3],
       [4, 5, 6]])

In [199]:
np.transpose(a,(1,0))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [200]:
b =np.arange(1,13).reshape(3,2,2)
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [201]:
b.T

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [202]:
np.transpose(b,(0,1,2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [203]:
np.transpose(b,(2,1,0))

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [204]:
np.transpose(b,(0,2,1))

array([[[ 1,  3],
        [ 2,  4]],

       [[ 5,  7],
        [ 6,  8]],

       [[ 9, 11],
        [10, 12]]])

In [206]:
c = np.arange(1,13).reshape(2,2,3)
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [207]:
c.T

array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])

In [208]:
c.transpose((1,2,0))

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [209]:
np.transpose(c)

array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])